# Generated by Django 5.1 on 2024-09-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=1)),
                ('cree_par', models.CharField(default=999, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_questionnaire',
            },
        ),
    ]
