# Generated by Django 5.1 on 2024-09-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionnaire',
            table='questionnaire',
        ),
    ]
