# Generated by Django 5.1 on 2024-09-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_questionnaire_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
