# Generated by Django 5.1 on 2024-09-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_questionnairedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='question',
        ),
    ]
