# Generated by Django 5.1 on 2024-09-28 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_remove_questionnaire_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresult',
            name='questionnaire_reponse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionnaireresult',
            name='questionnaire_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnairedetail'),
        ),
    ]
