# Generated by Django 5.1 on 2024-09-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_questionnaireresult_questionnaire_reponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='questionnaire',
        ),
    ]
