# Generated by Django 4.2.14 on 2024-07-31 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('anonyme', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'opinon',
            },
        ),
        migrations.CreateModel(
            name='OpinonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonne', models.CharField(blank=True, max_length=255)),
                ('plus', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('opinon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opinon.opinon')),
            ],
            options={
                'db_table': 'opinon_detail',
            },
        ),
    ]
