# Generated by Django 4.2.14 on 2024-08-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('opinon_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opinon.opinondetail')),
            ],
            options={
                'db_table': 'opinon_result',
            },
        ),
    ]
