# Generated by Django 5.1 on 2024-09-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('anonyme', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vote',
            },
        ),
        migrations.CreateModel(
            name='VoteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonne', models.CharField(blank=True, max_length=255)),
                ('plus', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.vote')),
            ],
            options={
                'db_table': 'vote_detail',
            },
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('vote_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votedetail')),
            ],
            options={
                'db_table': 'vote_result',
            },
        ),
    ]
