# Generated by Django 5.1 on 2024-09-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='cree_par',
            field=models.CharField(default=999, max_length=255),
        ),
    ]
